### PR TITLE
Refactor/tests

### PR DESCRIPTION
**Pull request by CalvinRodo**
Break tests out of Single Test Functions in Upload_Tests.go and Retrieve_Tests.go
Run `go fmt` in `pkg/server` folder

### CODE REVIEW

**Review by maxneuvians — APPROVED** [review]
Nice 🚀

**Review by tpjods — COMMENTED** [review]
Light review, looks ok

**Review by tpjods — COMMENTED** [review]
Light review

**Comment by tpjods** [comment]
Light review

**Comment by tpjods** [comment]
Light review

**Comment by tpjods** [comment]
Merge

**Pull request merged**
